import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../globals.css";
import AuthProvider from "../context/AuthProvider";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "../context/ThemeProvider";
import Navbar from "../ui/Navbar";
import Footer from "../ui/Footer";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // All available weights
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body
          className={`${poppins.variable} flex flex-col min-h-screen antialiased `}
        >
          <ThemeProvider>
            <Navbar />
            <div
              className="w-full px-4 sm:px-6 lg:px-14 xl:px-20 max-w-[1600px] flex-grow mx-auto"
              style={{ marginTop: "var(--navbar-height)" }}
            >
              <Toaster richColors />
              <main>{children}</main>
            </div>
            <Footer />
          </ThemeProvider>
        </body>
      </AuthProvider>
    </html>
  );
}
